/*
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v16/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v16
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v16.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; CampaignServiceMaximizeGainingFriendsBiddingSchemeオブジェクトは、キャンペーン目標単価(tCPF)の設定情報を表します。&lt;br&gt; このフィールドは、ADD時およびSET時に省略可能となり、REMOVE時に無視されます。&lt;br&gt; ※BiddingStrategyTypeがMAXIMIZE_GAINING_FRIENDSの場合、指定可能となります。     &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; CampaignServiceMaximizeGainingFriendsBiddingScheme object holds configuration information of Target CPF (tCPF) of campaign.&lt;br&gt; This field is optional in ADD and SET operation, and will be ignored in REMOVE operation.&lt;br&gt; *This field can only be specified (optional) when BiddingStrategyType is MAXIMIZE_GAINING_FRIENDS. &lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\"> CampaignServiceMaximizeGainingFriendsBiddingSchemeオブジェクトは、キャンペーン目標単価(tCPF)の設定情報を表します。<br> このフィールドは、ADD時およびSET時に省略可能となり、REMOVE時に無視されます。<br> ※BiddingStrategyTypeがMAXIMIZE_GAINING_FRIENDSの場合、指定可能となります。     </div> <div lang=\"en\"> CampaignServiceMaximizeGainingFriendsBiddingScheme object holds configuration information of Target CPF (tCPF) of campaign.<br> This field is optional in ADD and SET operation, and will be ignored in REMOVE operation.<br> *This field can only be specified (optional) when BiddingStrategyType is MAXIMIZE_GAINING_FRIENDS. </div> ")
@JsonPropertyOrder({
  CampaignServiceMaximizeGainingFriendsBiddingScheme.JSON_PROPERTY_TARGET_CPF
})
@JsonTypeName("CampaignServiceMaximizeGainingFriendsBiddingScheme")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class CampaignServiceMaximizeGainingFriendsBiddingScheme {
  public static final String JSON_PROPERTY_TARGET_CPF = "targetCpf";
  private Long targetCpf;

  public CampaignServiceMaximizeGainingFriendsBiddingScheme() { 
  }

  public CampaignServiceMaximizeGainingFriendsBiddingScheme targetCpf(Long targetCpf) {
    
    this.targetCpf = targetCpf;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; キャンペーン目標単価(tCPF)です。&lt;br&gt; ADDおよびSET時、このフィールドは任意で指定できます。&lt;br&gt; SET時、BiddingStrategyTypeにMAXIMIZE_GAINING_FRIENDSが指定されていて、targetCpfを指定しない場合、targetCpfの値がクリアされます。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; Target CPF (tCPF) of campaign.&lt;br&gt; This field can be optionally specified in ADD and SET operation.&lt;br&gt; If BiddingStrategyType is MAXIMIZE_GAINING_FRIENDS and targetCpf is not specified in SET operation, the value in this field will be cleared. &lt;/div&gt; 
   * @return targetCpf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\"> キャンペーン目標単価(tCPF)です。<br> ADDおよびSET時、このフィールドは任意で指定できます。<br> SET時、BiddingStrategyTypeにMAXIMIZE_GAINING_FRIENDSが指定されていて、targetCpfを指定しない場合、targetCpfの値がクリアされます。 </div> <div lang=\"en\"> Target CPF (tCPF) of campaign.<br> This field can be optionally specified in ADD and SET operation.<br> If BiddingStrategyType is MAXIMIZE_GAINING_FRIENDS and targetCpf is not specified in SET operation, the value in this field will be cleared. </div> ")
  @JsonProperty(JSON_PROPERTY_TARGET_CPF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTargetCpf() {
    return targetCpf;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_CPF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetCpf(Long targetCpf) {
    this.targetCpf = targetCpf;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignServiceMaximizeGainingFriendsBiddingScheme campaignServiceMaximizeGainingFriendsBiddingScheme = (CampaignServiceMaximizeGainingFriendsBiddingScheme) o;
    return Objects.equals(this.targetCpf, campaignServiceMaximizeGainingFriendsBiddingScheme.targetCpf);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetCpf);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignServiceMaximizeGainingFriendsBiddingScheme {\n");
    sb.append("    targetCpf: ").append(toIndentedString(targetCpf)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

