/*
 * LINEヤフー広告 ディスプレイ広告 API リファレンス / LY Ads Display Ads API Reference
 * <div lang=\"ja\">LINEヤフー広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in LY Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v17/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v17.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import jp.co.yahoo.adsdisplayapi.v17.model.RetargetingTagServiceApprovalStatus;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;RetargetingTagオブジェクトは、サイトリターゲティングのタグ情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;RetargetingTag object displays tag information for site retargeting.&lt;/div&gt; 
 */
@JsonPropertyOrder({
  RetargetingTag.JSON_PROPERTY_ACCOUNT_ID,
  RetargetingTag.JSON_PROPERTY_APPROVAL_STATUS,
  RetargetingTag.JSON_PROPERTY_RETARGETING_TAG_ID,
  RetargetingTag.JSON_PROPERTY_ADVANCED_TAG
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class RetargetingTag {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @jakarta.annotation.Nullable
  private Long accountId;

  public static final String JSON_PROPERTY_APPROVAL_STATUS = "approvalStatus";
  @jakarta.annotation.Nullable
  private RetargetingTagServiceApprovalStatus approvalStatus;

  public static final String JSON_PROPERTY_RETARGETING_TAG_ID = "retargetingTagId";
  @jakarta.annotation.Nullable
  private String retargetingTagId;

  public static final String JSON_PROPERTY_ADVANCED_TAG = "advancedTag";
  @jakarta.annotation.Nullable
  private String advancedTag;

  public RetargetingTag() {
  }

  public RetargetingTag accountId(@jakarta.annotation.Nullable Long accountId) {
    
    this.accountId = accountId;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アカウントIDです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account ID.&lt;/div&gt; 
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
  }

  public RetargetingTag approvalStatus(@jakarta.annotation.Nullable RetargetingTagServiceApprovalStatus approvalStatus) {
    
    this.approvalStatus = approvalStatus;
    return this;
  }

  /**
   * Get approvalStatus
   * @return approvalStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APPROVAL_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RetargetingTagServiceApprovalStatus getApprovalStatus() {
    return approvalStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_APPROVAL_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApprovalStatus(@jakarta.annotation.Nullable RetargetingTagServiceApprovalStatus approvalStatus) {
    this.approvalStatus = approvalStatus;
  }

  public RetargetingTag retargetingTagId(@jakarta.annotation.Nullable String retargetingTagId) {
    
    this.retargetingTagId = retargetingTagId;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;サイトリターゲティングのタグIDです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Tag ID for site retargeting.&lt;/div&gt; 
   * @return retargetingTagId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RETARGETING_TAG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRetargetingTagId() {
    return retargetingTagId;
  }


  @JsonProperty(value = JSON_PROPERTY_RETARGETING_TAG_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetargetingTagId(@jakarta.annotation.Nullable String retargetingTagId) {
    this.retargetingTagId = retargetingTagId;
  }

  public RetargetingTag advancedTag(@jakarta.annotation.Nullable String advancedTag) {
    
    this.advancedTag = advancedTag;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; リニューアル版のサイトリターゲティングタグは、従来のタグよりもブラウザーなどの環境の影響を受けづらい新しいフォーマットです。&lt;br&gt; 詳細は、「&lt;a href&#x3D;\&quot;https://ads-help.yahoo-net.jp/s/article/H000044890?language&#x3D;ja\&quot;&gt;サイトリターゲティングタグの取得とサイトへの設置&lt;/a&gt;」を参照してください。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; The new format of site retargeting tag avoids the impacts such as changes made to the browser. &lt;br&gt; More details are described on &lt;a href&#x3D;\&quot;https://ads-help.yahoo-net.jp/s/article/H000044890?language&#x3D;en_US\&quot;&gt;Acquire Site Retargeting Tag and Tagging on Site&lt;/a&gt;.&lt;br&gt; Although this field will be returned in the response, it will be ignored on input. &lt;/div&gt; 
   * @return advancedTag
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ADVANCED_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdvancedTag() {
    return advancedTag;
  }


  @JsonProperty(value = JSON_PROPERTY_ADVANCED_TAG, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvancedTag(@jakarta.annotation.Nullable String advancedTag) {
    this.advancedTag = advancedTag;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RetargetingTag retargetingTag = (RetargetingTag) o;
    return Objects.equals(this.accountId, retargetingTag.accountId) &&
        Objects.equals(this.approvalStatus, retargetingTag.approvalStatus) &&
        Objects.equals(this.retargetingTagId, retargetingTag.retargetingTagId) &&
        Objects.equals(this.advancedTag, retargetingTag.advancedTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, approvalStatus, retargetingTagId, advancedTag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RetargetingTag {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    approvalStatus: ").append(toIndentedString(approvalStatus)).append("\n");
    sb.append("    retargetingTagId: ").append(toIndentedString(retargetingTagId)).append("\n");
    sb.append("    advancedTag: ").append(toIndentedString(advancedTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

