/*
 * LINEヤフー広告 ディスプレイ広告 API リファレンス / LY Ads Display Ads API Reference
 * <div lang=\"ja\">LINEヤフー広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in LY Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v17/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v17
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v17.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import jp.co.yahoo.adsdisplayapi.v17.model.Error;
import jp.co.yahoo.adsdisplayapi.v17.model.Video;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;VideoServiceValueオブジェクトは、メソッドの実行結果（1Entity）を保持します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;VideoServiceValue object stores the execution result (1 Entity) of method.&lt;/div&gt; 
 */
@JsonPropertyOrder({
  VideoServiceValue.JSON_PROPERTY_ERRORS,
  VideoServiceValue.JSON_PROPERTY_OPERATION_SUCCEEDED,
  VideoServiceValue.JSON_PROPERTY_VIDEO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class VideoServiceValue {
  public static final String JSON_PROPERTY_ERRORS = "errors";
  @jakarta.annotation.Nullable
  private List<Error> errors;

  public static final String JSON_PROPERTY_OPERATION_SUCCEEDED = "operationSucceeded";
  @jakarta.annotation.Nullable
  private Boolean operationSucceeded;

  public static final String JSON_PROPERTY_VIDEO = "video";
  @jakarta.annotation.Nullable
  private Video video;

  public VideoServiceValue() {
  }

  public VideoServiceValue errors(@jakarta.annotation.Nullable List<Error> errors) {
    
    this.errors = errors;
    return this;
  }

  public VideoServiceValue addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Error> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@jakarta.annotation.Nullable List<Error> errors) {
    this.errors = errors;
  }

  public VideoServiceValue operationSucceeded(@jakarta.annotation.Nullable Boolean operationSucceeded) {
    
    this.operationSucceeded = operationSucceeded;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;処理結果です。trueの場合は、処理は成功しました。falseの場合は処理が失敗しています。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;The process results. If true, the process succeeded. If false, the process failed.&lt;/div&gt; 
   * @return operationSucceeded
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATION_SUCCEEDED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOperationSucceeded() {
    return operationSucceeded;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION_SUCCEEDED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationSucceeded(@jakarta.annotation.Nullable Boolean operationSucceeded) {
    this.operationSucceeded = operationSucceeded;
  }

  public VideoServiceValue video(@jakarta.annotation.Nullable Video video) {
    
    this.video = video;
    return this;
  }

  /**
   * Get video
   * @return video
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIDEO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Video getVideo() {
    return video;
  }


  @JsonProperty(value = JSON_PROPERTY_VIDEO, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVideo(@jakarta.annotation.Nullable Video video) {
    this.video = video;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VideoServiceValue videoServiceValue = (VideoServiceValue) o;
    return Objects.equals(this.errors, videoServiceValue.errors) &&
        Objects.equals(this.operationSucceeded, videoServiceValue.operationSucceeded) &&
        Objects.equals(this.video, videoServiceValue.video);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, operationSucceeded, video);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VideoServiceValue {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    operationSucceeded: ").append(toIndentedString(operationSucceeded)).append("\n");
    sb.append("    video: ").append(toIndentedString(video)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

