/*
 * LINEヤフー広告 ディスプレイ広告 API リファレンス / LY Ads Display Ads API Reference
 * <div lang=\"ja\">LINEヤフー広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in LY Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v20/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v20.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceAutoTaggingEnabled;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceClient;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceClientType;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceDeliveryStatus;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceIsCancellationPending;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceIsTestAccount;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServicePayment;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServicePrefectureCode;
import jp.co.yahoo.adsdisplayapi.v20.model.AccountManagementServiceStatus;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;AccountManagementオブジェクトは、アカウント情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AccountManagement objects serve account information.&lt;/div&gt; 
 */
@JsonPropertyOrder({
  AccountManagement.JSON_PROPERTY_ACCOUNT_ID,
  AccountManagement.JSON_PROPERTY_ACCOUNT_NAME,
  AccountManagement.JSON_PROPERTY_ACCOUNT_PAYMENT,
  AccountManagement.JSON_PROPERTY_AGENCY_PERSON_NAME,
  AccountManagement.JSON_PROPERTY_AGENCY_PREFECTURE_CODE,
  AccountManagement.JSON_PROPERTY_AUTO_TAGGING_ENABLED,
  AccountManagement.JSON_PROPERTY_CLIENT,
  AccountManagement.JSON_PROPERTY_CLIENT_TYPE,
  AccountManagement.JSON_PROPERTY_CONTACT_BIZ_ID,
  AccountManagement.JSON_PROPERTY_DELIVERY_STATUS,
  AccountManagement.JSON_PROPERTY_END_DATE,
  AccountManagement.JSON_PROPERTY_IS_TEST_ACCOUNT,
  AccountManagement.JSON_PROPERTY_IS_CANCELLATION_PENDING,
  AccountManagement.JSON_PROPERTY_START_DATE,
  AccountManagement.JSON_PROPERTY_STATUS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class AccountManagement {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @jakarta.annotation.Nullable
  private Long accountId;

  public static final String JSON_PROPERTY_ACCOUNT_NAME = "accountName";
  @jakarta.annotation.Nullable
  private String accountName;

  public static final String JSON_PROPERTY_ACCOUNT_PAYMENT = "accountPayment";
  @jakarta.annotation.Nullable
  private AccountManagementServicePayment accountPayment;

  public static final String JSON_PROPERTY_AGENCY_PERSON_NAME = "agencyPersonName";
  @jakarta.annotation.Nullable
  private String agencyPersonName;

  public static final String JSON_PROPERTY_AGENCY_PREFECTURE_CODE = "agencyPrefectureCode";
  @jakarta.annotation.Nullable
  private AccountManagementServicePrefectureCode agencyPrefectureCode;

  public static final String JSON_PROPERTY_AUTO_TAGGING_ENABLED = "autoTaggingEnabled";
  @jakarta.annotation.Nullable
  private AccountManagementServiceAutoTaggingEnabled autoTaggingEnabled;

  public static final String JSON_PROPERTY_CLIENT = "client";
  @jakarta.annotation.Nullable
  private AccountManagementServiceClient client;

  public static final String JSON_PROPERTY_CLIENT_TYPE = "clientType";
  @jakarta.annotation.Nullable
  private AccountManagementServiceClientType clientType;

  public static final String JSON_PROPERTY_CONTACT_BIZ_ID = "contactBizId";
  @jakarta.annotation.Nullable
  private String contactBizId;

  public static final String JSON_PROPERTY_DELIVERY_STATUS = "deliveryStatus";
  @jakarta.annotation.Nullable
  private AccountManagementServiceDeliveryStatus deliveryStatus;

  public static final String JSON_PROPERTY_END_DATE = "endDate";
  @jakarta.annotation.Nullable
  private String endDate;

  public static final String JSON_PROPERTY_IS_TEST_ACCOUNT = "isTestAccount";
  @jakarta.annotation.Nullable
  private AccountManagementServiceIsTestAccount isTestAccount;

  public static final String JSON_PROPERTY_IS_CANCELLATION_PENDING = "isCancellationPending";
  @jakarta.annotation.Nullable
  private AccountManagementServiceIsCancellationPending isCancellationPending;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
  @jakarta.annotation.Nullable
  private String startDate;

  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private AccountManagementServiceStatus status;

  public AccountManagement() {
  }

  public AccountManagement accountId(@jakarta.annotation.Nullable Long accountId) {
    
    this.accountId = accountId;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; アカウントIDです。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; Account ID.&lt;br&gt; Although this field will be returned in the response, it will be ignored on input. &lt;/div&gt; 
   * @return accountId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountId(@jakarta.annotation.Nullable Long accountId) {
    this.accountId = accountId;
  }

  public AccountManagement accountName(@jakarta.annotation.Nullable String accountName) {
    
    this.accountName = accountName;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アカウント名です。&lt;br&gt;このフィールドは、ADD時は必須となり、SET時は省略可能となります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account name.&lt;br&gt;This field is required in ADD operation, and will be optional in SET operation.&lt;/div&gt; 
   * @return accountName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAccountName() {
    return accountName;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountName(@jakarta.annotation.Nullable String accountName) {
    this.accountName = accountName;
  }

  public AccountManagement accountPayment(@jakarta.annotation.Nullable AccountManagementServicePayment accountPayment) {
    
    this.accountPayment = accountPayment;
    return this;
  }

  /**
   * Get accountPayment
   * @return accountPayment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_PAYMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServicePayment getAccountPayment() {
    return accountPayment;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_PAYMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountPayment(@jakarta.annotation.Nullable AccountManagementServicePayment accountPayment) {
    this.accountPayment = accountPayment;
  }

  public AccountManagement agencyPersonName(@jakarta.annotation.Nullable String agencyPersonName) {
    
    this.agencyPersonName = agencyPersonName;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; 代理店担当者名です。&lt;br&gt; ADDおよびSET時、このフィールドは省略可能となります。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; Agency person name.&lt;br&gt; This field is optional in ADD and SET operation. &lt;/div&gt; 
   * @return agencyPersonName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENCY_PERSON_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAgencyPersonName() {
    return agencyPersonName;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENCY_PERSON_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgencyPersonName(@jakarta.annotation.Nullable String agencyPersonName) {
    this.agencyPersonName = agencyPersonName;
  }

  public AccountManagement agencyPrefectureCode(@jakarta.annotation.Nullable AccountManagementServicePrefectureCode agencyPrefectureCode) {
    
    this.agencyPrefectureCode = agencyPrefectureCode;
    return this;
  }

  /**
   * Get agencyPrefectureCode
   * @return agencyPrefectureCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENCY_PREFECTURE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServicePrefectureCode getAgencyPrefectureCode() {
    return agencyPrefectureCode;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENCY_PREFECTURE_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgencyPrefectureCode(@jakarta.annotation.Nullable AccountManagementServicePrefectureCode agencyPrefectureCode) {
    this.agencyPrefectureCode = agencyPrefectureCode;
  }

  public AccountManagement autoTaggingEnabled(@jakarta.annotation.Nullable AccountManagementServiceAutoTaggingEnabled autoTaggingEnabled) {
    
    this.autoTaggingEnabled = autoTaggingEnabled;
    return this;
  }

  /**
   * Get autoTaggingEnabled
   * @return autoTaggingEnabled
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUTO_TAGGING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceAutoTaggingEnabled getAutoTaggingEnabled() {
    return autoTaggingEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_AUTO_TAGGING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAutoTaggingEnabled(@jakarta.annotation.Nullable AccountManagementServiceAutoTaggingEnabled autoTaggingEnabled) {
    this.autoTaggingEnabled = autoTaggingEnabled;
  }

  public AccountManagement client(@jakarta.annotation.Nullable AccountManagementServiceClient client) {
    
    this.client = client;
    return this;
  }

  /**
   * Get client
   * @return client
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceClient getClient() {
    return client;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClient(@jakarta.annotation.Nullable AccountManagementServiceClient client) {
    this.client = client;
  }

  public AccountManagement clientType(@jakarta.annotation.Nullable AccountManagementServiceClientType clientType) {
    
    this.clientType = clientType;
    return this;
  }

  /**
   * Get clientType
   * @return clientType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceClientType getClientType() {
    return clientType;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientType(@jakarta.annotation.Nullable AccountManagementServiceClientType clientType) {
    this.clientType = clientType;
  }

  public AccountManagement contactBizId(@jakarta.annotation.Nullable String contactBizId) {
    
    this.contactBizId = contactBizId;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; アカウント管理者のビジネスIDです。&lt;br&gt; このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; Contact business ID.&lt;br&gt; Although this field will be returned in the response, it will be ignored on input. &lt;/div&gt; 
   * @return contactBizId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTACT_BIZ_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getContactBizId() {
    return contactBizId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTACT_BIZ_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactBizId(@jakarta.annotation.Nullable String contactBizId) {
    this.contactBizId = contactBizId;
  }

  public AccountManagement deliveryStatus(@jakarta.annotation.Nullable AccountManagementServiceDeliveryStatus deliveryStatus) {
    
    this.deliveryStatus = deliveryStatus;
    return this;
  }

  /**
   * Get deliveryStatus
   * @return deliveryStatus
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELIVERY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceDeliveryStatus getDeliveryStatus() {
    return deliveryStatus;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveryStatus(@jakarta.annotation.Nullable AccountManagementServiceDeliveryStatus deliveryStatus) {
    this.deliveryStatus = deliveryStatus;
  }

  public AccountManagement endDate(@jakarta.annotation.Nullable String endDate) {
    
    this.endDate = endDate;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; 終了日&lt;br&gt; YYYYMMDD形式で指定 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; End date&lt;br&gt; YYYYMMDD &lt;/div&gt; 
   * @return endDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEndDate() {
    return endDate;
  }


  @JsonProperty(value = JSON_PROPERTY_END_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(@jakarta.annotation.Nullable String endDate) {
    this.endDate = endDate;
  }

  public AccountManagement isTestAccount(@jakarta.annotation.Nullable AccountManagementServiceIsTestAccount isTestAccount) {
    
    this.isTestAccount = isTestAccount;
    return this;
  }

  /**
   * Get isTestAccount
   * @return isTestAccount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_TEST_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceIsTestAccount getIsTestAccount() {
    return isTestAccount;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_TEST_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsTestAccount(@jakarta.annotation.Nullable AccountManagementServiceIsTestAccount isTestAccount) {
    this.isTestAccount = isTestAccount;
  }

  public AccountManagement isCancellationPending(@jakarta.annotation.Nullable AccountManagementServiceIsCancellationPending isCancellationPending) {
    
    this.isCancellationPending = isCancellationPending;
    return this;
  }

  /**
   * Get isCancellationPending
   * @return isCancellationPending
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_CANCELLATION_PENDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceIsCancellationPending getIsCancellationPending() {
    return isCancellationPending;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_CANCELLATION_PENDING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsCancellationPending(@jakarta.annotation.Nullable AccountManagementServiceIsCancellationPending isCancellationPending) {
    this.isCancellationPending = isCancellationPending;
  }

  public AccountManagement startDate(@jakarta.annotation.Nullable String startDate) {
    
    this.startDate = startDate;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt; 開始日（YYYYMMDD形式）&lt;br&gt; 自動でADD時の日付が登録される。 &lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt; Start date&lt;br&gt; YYYYMMDD&lt;br&gt; This field is automatically registered in ADD operation &lt;/div&gt; 
   * @return startDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStartDate() {
    return startDate;
  }


  @JsonProperty(value = JSON_PROPERTY_START_DATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartDate(@jakarta.annotation.Nullable String startDate) {
    this.startDate = startDate;
  }

  public AccountManagement status(@jakarta.annotation.Nullable AccountManagementServiceStatus status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public AccountManagementServiceStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable AccountManagementServiceStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountManagement accountManagement = (AccountManagement) o;
    return Objects.equals(this.accountId, accountManagement.accountId) &&
        Objects.equals(this.accountName, accountManagement.accountName) &&
        Objects.equals(this.accountPayment, accountManagement.accountPayment) &&
        Objects.equals(this.agencyPersonName, accountManagement.agencyPersonName) &&
        Objects.equals(this.agencyPrefectureCode, accountManagement.agencyPrefectureCode) &&
        Objects.equals(this.autoTaggingEnabled, accountManagement.autoTaggingEnabled) &&
        Objects.equals(this.client, accountManagement.client) &&
        Objects.equals(this.clientType, accountManagement.clientType) &&
        Objects.equals(this.contactBizId, accountManagement.contactBizId) &&
        Objects.equals(this.deliveryStatus, accountManagement.deliveryStatus) &&
        Objects.equals(this.endDate, accountManagement.endDate) &&
        Objects.equals(this.isTestAccount, accountManagement.isTestAccount) &&
        Objects.equals(this.isCancellationPending, accountManagement.isCancellationPending) &&
        Objects.equals(this.startDate, accountManagement.startDate) &&
        Objects.equals(this.status, accountManagement.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountName, accountPayment, agencyPersonName, agencyPrefectureCode, autoTaggingEnabled, client, clientType, contactBizId, deliveryStatus, endDate, isTestAccount, isCancellationPending, startDate, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountManagement {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountPayment: ").append(toIndentedString(accountPayment)).append("\n");
    sb.append("    agencyPersonName: ").append(toIndentedString(agencyPersonName)).append("\n");
    sb.append("    agencyPrefectureCode: ").append(toIndentedString(agencyPrefectureCode)).append("\n");
    sb.append("    autoTaggingEnabled: ").append(toIndentedString(autoTaggingEnabled)).append("\n");
    sb.append("    client: ").append(toIndentedString(client)).append("\n");
    sb.append("    clientType: ").append(toIndentedString(clientType)).append("\n");
    sb.append("    contactBizId: ").append(toIndentedString(contactBizId)).append("\n");
    sb.append("    deliveryStatus: ").append(toIndentedString(deliveryStatus)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    isTestAccount: ").append(toIndentedString(isTestAccount)).append("\n");
    sb.append("    isCancellationPending: ").append(toIndentedString(isCancellationPending)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

