/*
 * LINEヤフー広告 ディスプレイ広告 API リファレンス / LY Ads Display Ads API Reference
 * <div lang=\"ja\">LINEヤフー広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in LY Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v20/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v20.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import jp.co.yahoo.adsdisplayapi.v20.model.AuditLogServiceJobStatus;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;getメソッドの検索条件（実行パラメータ）を保持するオブジェクトです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;AuditLogServiceSelector object is container storing the search conditions of get method (execution parameter).&lt;/div&gt; 
 */
@JsonPropertyOrder({
  AuditLogServiceSelector.JSON_PROPERTY_ACCOUNT_ID,
  AuditLogServiceSelector.JSON_PROPERTY_AUDIT_LOG_JOB_IDS,
  AuditLogServiceSelector.JSON_PROPERTY_JOB_STATUSES,
  AuditLogServiceSelector.JSON_PROPERTY_NUMBER_RESULTS,
  AuditLogServiceSelector.JSON_PROPERTY_START_INDEX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class AuditLogServiceSelector {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @jakarta.annotation.Nonnull
  private Long accountId;

  public static final String JSON_PROPERTY_AUDIT_LOG_JOB_IDS = "auditLogJobIds";
  @jakarta.annotation.Nullable
  private List<Long> auditLogJobIds;

  public static final String JSON_PROPERTY_JOB_STATUSES = "jobStatuses";
  @jakarta.annotation.Nullable
  private List<AuditLogServiceJobStatus> jobStatuses;

  public static final String JSON_PROPERTY_NUMBER_RESULTS = "numberResults";
  @jakarta.annotation.Nullable
  private Integer numberResults = 500;

  public static final String JSON_PROPERTY_START_INDEX = "startIndex";
  @jakarta.annotation.Nullable
  private Integer startIndex = 1;

  public AuditLogServiceSelector() {
  }

  public AuditLogServiceSelector accountId(@jakarta.annotation.Nonnull Long accountId) {
    
    this.accountId = accountId;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;アカウントIDです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Account ID.&lt;/div&gt; 
   * @return accountId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(@jakarta.annotation.Nonnull Long accountId) {
    this.accountId = accountId;
  }

  public AuditLogServiceSelector auditLogJobIds(@jakarta.annotation.Nullable List<Long> auditLogJobIds) {
    
    this.auditLogJobIds = auditLogJobIds;
    return this;
  }

  public AuditLogServiceSelector addAuditLogJobIdsItem(Long auditLogJobIdsItem) {
    if (this.auditLogJobIds == null) {
      this.auditLogJobIds = new ArrayList<>();
    }
    this.auditLogJobIds.add(auditLogJobIdsItem);
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ジョブIDです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;The job ID.&lt;/div&gt; 
   * @return auditLogJobIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AUDIT_LOG_JOB_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getAuditLogJobIds() {
    return auditLogJobIds;
  }


  @JsonProperty(value = JSON_PROPERTY_AUDIT_LOG_JOB_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAuditLogJobIds(@jakarta.annotation.Nullable List<Long> auditLogJobIds) {
    this.auditLogJobIds = auditLogJobIds;
  }

  public AuditLogServiceSelector jobStatuses(@jakarta.annotation.Nullable List<AuditLogServiceJobStatus> jobStatuses) {
    
    this.jobStatuses = jobStatuses;
    return this;
  }

  public AuditLogServiceSelector addJobStatusesItem(AuditLogServiceJobStatus jobStatusesItem) {
    if (this.jobStatuses == null) {
      this.jobStatuses = new ArrayList<>();
    }
    this.jobStatuses.add(jobStatusesItem);
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ジョブステータスです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;The job status information.&lt;/div&gt; 
   * @return jobStatuses
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_JOB_STATUSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AuditLogServiceJobStatus> getJobStatuses() {
    return jobStatuses;
  }


  @JsonProperty(value = JSON_PROPERTY_JOB_STATUSES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setJobStatuses(@jakarta.annotation.Nullable List<AuditLogServiceJobStatus> jobStatuses) {
    this.jobStatuses = jobStatuses;
  }

  public AuditLogServiceSelector numberResults(@jakarta.annotation.Nullable Integer numberResults) {
    
    this.numberResults = numberResults;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;開始位置から取得する結果の数。このフィールドは、1以上を指定する必要があります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;The number of results to retrieve starting from the initial position. This field must be greater than or equal to 1.&lt;/div&gt; 
   * minimum: 1
   * maximum: 500
   * @return numberResults
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUMBER_RESULTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getNumberResults() {
    return numberResults;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER_RESULTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumberResults(@jakarta.annotation.Nullable Integer numberResults) {
    this.numberResults = numberResults;
  }

  public AuditLogServiceSelector startIndex(@jakarta.annotation.Nullable Integer startIndex) {
    
    this.startIndex = startIndex;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;取得を開始する結果セット内の位置。このフィールドは、0以上を指定する必要があります。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;The position within the result set where retrieval begins. This field must be greater than or equal to 0.&lt;/div&gt; 
   * minimum: 1
   * @return startIndex
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartIndex() {
    return startIndex;
  }


  @JsonProperty(value = JSON_PROPERTY_START_INDEX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartIndex(@jakarta.annotation.Nullable Integer startIndex) {
    this.startIndex = startIndex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuditLogServiceSelector auditLogServiceSelector = (AuditLogServiceSelector) o;
    return Objects.equals(this.accountId, auditLogServiceSelector.accountId) &&
        Objects.equals(this.auditLogJobIds, auditLogServiceSelector.auditLogJobIds) &&
        Objects.equals(this.jobStatuses, auditLogServiceSelector.jobStatuses) &&
        Objects.equals(this.numberResults, auditLogServiceSelector.numberResults) &&
        Objects.equals(this.startIndex, auditLogServiceSelector.startIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, auditLogJobIds, jobStatuses, numberResults, startIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuditLogServiceSelector {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    auditLogJobIds: ").append(toIndentedString(auditLogJobIds)).append("\n");
    sb.append("    jobStatuses: ").append(toIndentedString(jobStatuses)).append("\n");
    sb.append("    numberResults: ").append(toIndentedString(numberResults)).append("\n");
    sb.append("    startIndex: ").append(toIndentedString(startIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

