/*
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v5/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v5.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceAdScheduleTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceAgeTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceAppTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceAudienceCategoryTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceCarrierTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceDeviceTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceGenderTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceGeoTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceInterestCategoryTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceOsTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceOsVersionTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServicePlacementCategoryDetailTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServicePlacementTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceSearchTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceSiteCategoryTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceSiteRetargetingTarget;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceTargetSetting;
import jp.co.yahoo.adsdisplayapi.v5.model.StatsServiceTargetType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;StatsServiceTargetオブジェクトは、ターゲット設定情報を保持します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;StatsServiceTarget object holds configuration information of StatsServiceTargeting.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">StatsServiceTargetオブジェクトは、ターゲット設定情報を保持します。</div> <div lang=\"en\">StatsServiceTarget object holds configuration information of StatsServiceTargeting.</div> ")
@JsonPropertyOrder({
  StatsServiceTarget.JSON_PROPERTY_AD_SCHEDULE_TARGET,
  StatsServiceTarget.JSON_PROPERTY_AGE_TARGET,
  StatsServiceTarget.JSON_PROPERTY_APP_TARGET,
  StatsServiceTarget.JSON_PROPERTY_AUDIENCE_CATEGORY_TARGET,
  StatsServiceTarget.JSON_PROPERTY_CARRIER_TARGET,
  StatsServiceTarget.JSON_PROPERTY_DEVICE_TARGET,
  StatsServiceTarget.JSON_PROPERTY_GENDER_TARGET,
  StatsServiceTarget.JSON_PROPERTY_GEO_TARGET,
  StatsServiceTarget.JSON_PROPERTY_INTEREST_CATEGORY_TARGET,
  StatsServiceTarget.JSON_PROPERTY_OS_TARGET,
  StatsServiceTarget.JSON_PROPERTY_OS_VERSION_TARGET,
  StatsServiceTarget.JSON_PROPERTY_PLACEMENT_TARGET,
  StatsServiceTarget.JSON_PROPERTY_SEARCH_TARGET,
  StatsServiceTarget.JSON_PROPERTY_SITE_CATEGORY_TARGET,
  StatsServiceTarget.JSON_PROPERTY_SITE_RETARGETING_TARGET,
  StatsServiceTarget.JSON_PROPERTY_PLACEMENT_CATEGORY_DETAIL_TARGET,
  StatsServiceTarget.JSON_PROPERTY_TARGET_ID,
  StatsServiceTarget.JSON_PROPERTY_TARGET_SETTING,
  StatsServiceTarget.JSON_PROPERTY_TARGET_TYPE
})
@JsonTypeName("StatsServiceTarget")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class StatsServiceTarget {
  public static final String JSON_PROPERTY_AD_SCHEDULE_TARGET = "adScheduleTarget";
  private StatsServiceAdScheduleTarget adScheduleTarget;

  public static final String JSON_PROPERTY_AGE_TARGET = "ageTarget";
  private StatsServiceAgeTarget ageTarget;

  public static final String JSON_PROPERTY_APP_TARGET = "appTarget";
  private StatsServiceAppTarget appTarget;

  public static final String JSON_PROPERTY_AUDIENCE_CATEGORY_TARGET = "audienceCategoryTarget";
  private StatsServiceAudienceCategoryTarget audienceCategoryTarget;

  public static final String JSON_PROPERTY_CARRIER_TARGET = "carrierTarget";
  private StatsServiceCarrierTarget carrierTarget;

  public static final String JSON_PROPERTY_DEVICE_TARGET = "deviceTarget";
  private StatsServiceDeviceTarget deviceTarget;

  public static final String JSON_PROPERTY_GENDER_TARGET = "genderTarget";
  private StatsServiceGenderTarget genderTarget;

  public static final String JSON_PROPERTY_GEO_TARGET = "geoTarget";
  private StatsServiceGeoTarget geoTarget;

  public static final String JSON_PROPERTY_INTEREST_CATEGORY_TARGET = "interestCategoryTarget";
  private StatsServiceInterestCategoryTarget interestCategoryTarget;

  public static final String JSON_PROPERTY_OS_TARGET = "osTarget";
  private StatsServiceOsTarget osTarget;

  public static final String JSON_PROPERTY_OS_VERSION_TARGET = "osVersionTarget";
  private StatsServiceOsVersionTarget osVersionTarget;

  public static final String JSON_PROPERTY_PLACEMENT_TARGET = "placementTarget";
  private StatsServicePlacementTarget placementTarget;

  public static final String JSON_PROPERTY_SEARCH_TARGET = "searchTarget";
  private StatsServiceSearchTarget searchTarget;

  public static final String JSON_PROPERTY_SITE_CATEGORY_TARGET = "siteCategoryTarget";
  private StatsServiceSiteCategoryTarget siteCategoryTarget;

  public static final String JSON_PROPERTY_SITE_RETARGETING_TARGET = "siteRetargetingTarget";
  private StatsServiceSiteRetargetingTarget siteRetargetingTarget;

  public static final String JSON_PROPERTY_PLACEMENT_CATEGORY_DETAIL_TARGET = "placementCategoryDetailTarget";
  private StatsServicePlacementCategoryDetailTarget placementCategoryDetailTarget;

  public static final String JSON_PROPERTY_TARGET_ID = "targetId";
  private String targetId;

  public static final String JSON_PROPERTY_TARGET_SETTING = "targetSetting";
  private StatsServiceTargetSetting targetSetting;

  public static final String JSON_PROPERTY_TARGET_TYPE = "targetType";
  private StatsServiceTargetType targetType;

  public StatsServiceTarget() { 
  }

  public StatsServiceTarget adScheduleTarget(StatsServiceAdScheduleTarget adScheduleTarget) {
    
    this.adScheduleTarget = adScheduleTarget;
    return this;
  }

   /**
   * Get adScheduleTarget
   * @return adScheduleTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AD_SCHEDULE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceAdScheduleTarget getAdScheduleTarget() {
    return adScheduleTarget;
  }


  @JsonProperty(JSON_PROPERTY_AD_SCHEDULE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdScheduleTarget(StatsServiceAdScheduleTarget adScheduleTarget) {
    this.adScheduleTarget = adScheduleTarget;
  }


  public StatsServiceTarget ageTarget(StatsServiceAgeTarget ageTarget) {
    
    this.ageTarget = ageTarget;
    return this;
  }

   /**
   * Get ageTarget
   * @return ageTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AGE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceAgeTarget getAgeTarget() {
    return ageTarget;
  }


  @JsonProperty(JSON_PROPERTY_AGE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgeTarget(StatsServiceAgeTarget ageTarget) {
    this.ageTarget = ageTarget;
  }


  public StatsServiceTarget appTarget(StatsServiceAppTarget appTarget) {
    
    this.appTarget = appTarget;
    return this;
  }

   /**
   * Get appTarget
   * @return appTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_APP_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceAppTarget getAppTarget() {
    return appTarget;
  }


  @JsonProperty(JSON_PROPERTY_APP_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppTarget(StatsServiceAppTarget appTarget) {
    this.appTarget = appTarget;
  }


  public StatsServiceTarget audienceCategoryTarget(StatsServiceAudienceCategoryTarget audienceCategoryTarget) {
    
    this.audienceCategoryTarget = audienceCategoryTarget;
    return this;
  }

   /**
   * Get audienceCategoryTarget
   * @return audienceCategoryTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_AUDIENCE_CATEGORY_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceAudienceCategoryTarget getAudienceCategoryTarget() {
    return audienceCategoryTarget;
  }


  @JsonProperty(JSON_PROPERTY_AUDIENCE_CATEGORY_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAudienceCategoryTarget(StatsServiceAudienceCategoryTarget audienceCategoryTarget) {
    this.audienceCategoryTarget = audienceCategoryTarget;
  }


  public StatsServiceTarget carrierTarget(StatsServiceCarrierTarget carrierTarget) {
    
    this.carrierTarget = carrierTarget;
    return this;
  }

   /**
   * Get carrierTarget
   * @return carrierTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CARRIER_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceCarrierTarget getCarrierTarget() {
    return carrierTarget;
  }


  @JsonProperty(JSON_PROPERTY_CARRIER_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCarrierTarget(StatsServiceCarrierTarget carrierTarget) {
    this.carrierTarget = carrierTarget;
  }


  public StatsServiceTarget deviceTarget(StatsServiceDeviceTarget deviceTarget) {
    
    this.deviceTarget = deviceTarget;
    return this;
  }

   /**
   * Get deviceTarget
   * @return deviceTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DEVICE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceDeviceTarget getDeviceTarget() {
    return deviceTarget;
  }


  @JsonProperty(JSON_PROPERTY_DEVICE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeviceTarget(StatsServiceDeviceTarget deviceTarget) {
    this.deviceTarget = deviceTarget;
  }


  public StatsServiceTarget genderTarget(StatsServiceGenderTarget genderTarget) {
    
    this.genderTarget = genderTarget;
    return this;
  }

   /**
   * Get genderTarget
   * @return genderTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GENDER_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceGenderTarget getGenderTarget() {
    return genderTarget;
  }


  @JsonProperty(JSON_PROPERTY_GENDER_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGenderTarget(StatsServiceGenderTarget genderTarget) {
    this.genderTarget = genderTarget;
  }


  public StatsServiceTarget geoTarget(StatsServiceGeoTarget geoTarget) {
    
    this.geoTarget = geoTarget;
    return this;
  }

   /**
   * Get geoTarget
   * @return geoTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GEO_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceGeoTarget getGeoTarget() {
    return geoTarget;
  }


  @JsonProperty(JSON_PROPERTY_GEO_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGeoTarget(StatsServiceGeoTarget geoTarget) {
    this.geoTarget = geoTarget;
  }


  public StatsServiceTarget interestCategoryTarget(StatsServiceInterestCategoryTarget interestCategoryTarget) {
    
    this.interestCategoryTarget = interestCategoryTarget;
    return this;
  }

   /**
   * Get interestCategoryTarget
   * @return interestCategoryTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INTEREST_CATEGORY_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceInterestCategoryTarget getInterestCategoryTarget() {
    return interestCategoryTarget;
  }


  @JsonProperty(JSON_PROPERTY_INTEREST_CATEGORY_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInterestCategoryTarget(StatsServiceInterestCategoryTarget interestCategoryTarget) {
    this.interestCategoryTarget = interestCategoryTarget;
  }


  public StatsServiceTarget osTarget(StatsServiceOsTarget osTarget) {
    
    this.osTarget = osTarget;
    return this;
  }

   /**
   * Get osTarget
   * @return osTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OS_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceOsTarget getOsTarget() {
    return osTarget;
  }


  @JsonProperty(JSON_PROPERTY_OS_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsTarget(StatsServiceOsTarget osTarget) {
    this.osTarget = osTarget;
  }


  public StatsServiceTarget osVersionTarget(StatsServiceOsVersionTarget osVersionTarget) {
    
    this.osVersionTarget = osVersionTarget;
    return this;
  }

   /**
   * Get osVersionTarget
   * @return osVersionTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OS_VERSION_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceOsVersionTarget getOsVersionTarget() {
    return osVersionTarget;
  }


  @JsonProperty(JSON_PROPERTY_OS_VERSION_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOsVersionTarget(StatsServiceOsVersionTarget osVersionTarget) {
    this.osVersionTarget = osVersionTarget;
  }


  public StatsServiceTarget placementTarget(StatsServicePlacementTarget placementTarget) {
    
    this.placementTarget = placementTarget;
    return this;
  }

   /**
   * Get placementTarget
   * @return placementTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLACEMENT_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServicePlacementTarget getPlacementTarget() {
    return placementTarget;
  }


  @JsonProperty(JSON_PROPERTY_PLACEMENT_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlacementTarget(StatsServicePlacementTarget placementTarget) {
    this.placementTarget = placementTarget;
  }


  public StatsServiceTarget searchTarget(StatsServiceSearchTarget searchTarget) {
    
    this.searchTarget = searchTarget;
    return this;
  }

   /**
   * Get searchTarget
   * @return searchTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SEARCH_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceSearchTarget getSearchTarget() {
    return searchTarget;
  }


  @JsonProperty(JSON_PROPERTY_SEARCH_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSearchTarget(StatsServiceSearchTarget searchTarget) {
    this.searchTarget = searchTarget;
  }


  public StatsServiceTarget siteCategoryTarget(StatsServiceSiteCategoryTarget siteCategoryTarget) {
    
    this.siteCategoryTarget = siteCategoryTarget;
    return this;
  }

   /**
   * Get siteCategoryTarget
   * @return siteCategoryTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SITE_CATEGORY_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceSiteCategoryTarget getSiteCategoryTarget() {
    return siteCategoryTarget;
  }


  @JsonProperty(JSON_PROPERTY_SITE_CATEGORY_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSiteCategoryTarget(StatsServiceSiteCategoryTarget siteCategoryTarget) {
    this.siteCategoryTarget = siteCategoryTarget;
  }


  public StatsServiceTarget siteRetargetingTarget(StatsServiceSiteRetargetingTarget siteRetargetingTarget) {
    
    this.siteRetargetingTarget = siteRetargetingTarget;
    return this;
  }

   /**
   * Get siteRetargetingTarget
   * @return siteRetargetingTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_SITE_RETARGETING_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceSiteRetargetingTarget getSiteRetargetingTarget() {
    return siteRetargetingTarget;
  }


  @JsonProperty(JSON_PROPERTY_SITE_RETARGETING_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSiteRetargetingTarget(StatsServiceSiteRetargetingTarget siteRetargetingTarget) {
    this.siteRetargetingTarget = siteRetargetingTarget;
  }


  public StatsServiceTarget placementCategoryDetailTarget(StatsServicePlacementCategoryDetailTarget placementCategoryDetailTarget) {
    
    this.placementCategoryDetailTarget = placementCategoryDetailTarget;
    return this;
  }

   /**
   * Get placementCategoryDetailTarget
   * @return placementCategoryDetailTarget
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLACEMENT_CATEGORY_DETAIL_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServicePlacementCategoryDetailTarget getPlacementCategoryDetailTarget() {
    return placementCategoryDetailTarget;
  }


  @JsonProperty(JSON_PROPERTY_PLACEMENT_CATEGORY_DETAIL_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlacementCategoryDetailTarget(StatsServicePlacementCategoryDetailTarget placementCategoryDetailTarget) {
    this.placementCategoryDetailTarget = placementCategoryDetailTarget;
  }


  public StatsServiceTarget targetId(String targetId) {
    
    this.targetId = targetId;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;ターゲットID&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;StatsServiceTarget ID&lt;/div&gt; 
   * @return targetId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">ターゲットID</div> <div lang=\"en\">StatsServiceTarget ID</div> ")
  @JsonProperty(JSON_PROPERTY_TARGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTargetId() {
    return targetId;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetId(String targetId) {
    this.targetId = targetId;
  }


  public StatsServiceTarget targetSetting(StatsServiceTargetSetting targetSetting) {
    
    this.targetSetting = targetSetting;
    return this;
  }

   /**
   * Get targetSetting
   * @return targetSetting
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARGET_SETTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceTargetSetting getTargetSetting() {
    return targetSetting;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_SETTING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetSetting(StatsServiceTargetSetting targetSetting) {
    this.targetSetting = targetSetting;
  }


  public StatsServiceTarget targetType(StatsServiceTargetType targetType) {
    
    this.targetType = targetType;
    return this;
  }

   /**
   * Get targetType
   * @return targetType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TARGET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatsServiceTargetType getTargetType() {
    return targetType;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetType(StatsServiceTargetType targetType) {
    this.targetType = targetType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatsServiceTarget statsServiceTarget = (StatsServiceTarget) o;
    return Objects.equals(this.adScheduleTarget, statsServiceTarget.adScheduleTarget) &&
        Objects.equals(this.ageTarget, statsServiceTarget.ageTarget) &&
        Objects.equals(this.appTarget, statsServiceTarget.appTarget) &&
        Objects.equals(this.audienceCategoryTarget, statsServiceTarget.audienceCategoryTarget) &&
        Objects.equals(this.carrierTarget, statsServiceTarget.carrierTarget) &&
        Objects.equals(this.deviceTarget, statsServiceTarget.deviceTarget) &&
        Objects.equals(this.genderTarget, statsServiceTarget.genderTarget) &&
        Objects.equals(this.geoTarget, statsServiceTarget.geoTarget) &&
        Objects.equals(this.interestCategoryTarget, statsServiceTarget.interestCategoryTarget) &&
        Objects.equals(this.osTarget, statsServiceTarget.osTarget) &&
        Objects.equals(this.osVersionTarget, statsServiceTarget.osVersionTarget) &&
        Objects.equals(this.placementTarget, statsServiceTarget.placementTarget) &&
        Objects.equals(this.searchTarget, statsServiceTarget.searchTarget) &&
        Objects.equals(this.siteCategoryTarget, statsServiceTarget.siteCategoryTarget) &&
        Objects.equals(this.siteRetargetingTarget, statsServiceTarget.siteRetargetingTarget) &&
        Objects.equals(this.placementCategoryDetailTarget, statsServiceTarget.placementCategoryDetailTarget) &&
        Objects.equals(this.targetId, statsServiceTarget.targetId) &&
        Objects.equals(this.targetSetting, statsServiceTarget.targetSetting) &&
        Objects.equals(this.targetType, statsServiceTarget.targetType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adScheduleTarget, ageTarget, appTarget, audienceCategoryTarget, carrierTarget, deviceTarget, genderTarget, geoTarget, interestCategoryTarget, osTarget, osVersionTarget, placementTarget, searchTarget, siteCategoryTarget, siteRetargetingTarget, placementCategoryDetailTarget, targetId, targetSetting, targetType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatsServiceTarget {\n");
    sb.append("    adScheduleTarget: ").append(toIndentedString(adScheduleTarget)).append("\n");
    sb.append("    ageTarget: ").append(toIndentedString(ageTarget)).append("\n");
    sb.append("    appTarget: ").append(toIndentedString(appTarget)).append("\n");
    sb.append("    audienceCategoryTarget: ").append(toIndentedString(audienceCategoryTarget)).append("\n");
    sb.append("    carrierTarget: ").append(toIndentedString(carrierTarget)).append("\n");
    sb.append("    deviceTarget: ").append(toIndentedString(deviceTarget)).append("\n");
    sb.append("    genderTarget: ").append(toIndentedString(genderTarget)).append("\n");
    sb.append("    geoTarget: ").append(toIndentedString(geoTarget)).append("\n");
    sb.append("    interestCategoryTarget: ").append(toIndentedString(interestCategoryTarget)).append("\n");
    sb.append("    osTarget: ").append(toIndentedString(osTarget)).append("\n");
    sb.append("    osVersionTarget: ").append(toIndentedString(osVersionTarget)).append("\n");
    sb.append("    placementTarget: ").append(toIndentedString(placementTarget)).append("\n");
    sb.append("    searchTarget: ").append(toIndentedString(searchTarget)).append("\n");
    sb.append("    siteCategoryTarget: ").append(toIndentedString(siteCategoryTarget)).append("\n");
    sb.append("    siteRetargetingTarget: ").append(toIndentedString(siteRetargetingTarget)).append("\n");
    sb.append("    placementCategoryDetailTarget: ").append(toIndentedString(placementCategoryDetailTarget)).append("\n");
    sb.append("    targetId: ").append(toIndentedString(targetId)).append("\n");
    sb.append("    targetSetting: ").append(toIndentedString(targetSetting)).append("\n");
    sb.append("    targetType: ").append(toIndentedString(targetType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

