/*
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v13/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v13
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v13.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import jp.co.yahoo.adsdisplayapi.v13.model.RecommendationServiceDailyBudgetSmallCampaign;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;RecommendationServiceDailyBudgetSmallオブジェクトは、1日の予算が5,000円未満のキャンペーンに関する最適化提案の情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;RecommendationServiceDailyBudgetSmall object describes recommendation information about the campaign with less than 5,000 JPY daily budget.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">RecommendationServiceDailyBudgetSmallオブジェクトは、1日の予算が5,000円未満のキャンペーンに関する最適化提案の情報を表します。</div> <div lang=\"en\">RecommendationServiceDailyBudgetSmall object describes recommendation information about the campaign with less than 5,000 JPY daily budget.</div> ")
@JsonPropertyOrder({
  RecommendationServiceDailyBudgetSmall.JSON_PROPERTY_DAILY_BUDGET_SMALL_CAMPAIGN_LIST
})
@JsonTypeName("RecommendationServiceDailyBudgetSmall")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class RecommendationServiceDailyBudgetSmall {
  public static final String JSON_PROPERTY_DAILY_BUDGET_SMALL_CAMPAIGN_LIST = "dailyBudgetSmallCampaignList";
  private List<RecommendationServiceDailyBudgetSmallCampaign> dailyBudgetSmallCampaignList = null;

  public RecommendationServiceDailyBudgetSmall() { 
  }

  public RecommendationServiceDailyBudgetSmall dailyBudgetSmallCampaignList(List<RecommendationServiceDailyBudgetSmallCampaign> dailyBudgetSmallCampaignList) {
    
    this.dailyBudgetSmallCampaignList = dailyBudgetSmallCampaignList;
    return this;
  }

  public RecommendationServiceDailyBudgetSmall addDailyBudgetSmallCampaignListItem(RecommendationServiceDailyBudgetSmallCampaign dailyBudgetSmallCampaignListItem) {
    if (this.dailyBudgetSmallCampaignList == null) {
      this.dailyBudgetSmallCampaignList = new ArrayList<>();
    }
    this.dailyBudgetSmallCampaignList.add(dailyBudgetSmallCampaignListItem);
    return this;
  }

   /**
   * Get dailyBudgetSmallCampaignList
   * @return dailyBudgetSmallCampaignList
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DAILY_BUDGET_SMALL_CAMPAIGN_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<RecommendationServiceDailyBudgetSmallCampaign> getDailyBudgetSmallCampaignList() {
    return dailyBudgetSmallCampaignList;
  }


  @JsonProperty(JSON_PROPERTY_DAILY_BUDGET_SMALL_CAMPAIGN_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDailyBudgetSmallCampaignList(List<RecommendationServiceDailyBudgetSmallCampaign> dailyBudgetSmallCampaignList) {
    this.dailyBudgetSmallCampaignList = dailyBudgetSmallCampaignList;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationServiceDailyBudgetSmall recommendationServiceDailyBudgetSmall = (RecommendationServiceDailyBudgetSmall) o;
    return Objects.equals(this.dailyBudgetSmallCampaignList, recommendationServiceDailyBudgetSmall.dailyBudgetSmallCampaignList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dailyBudgetSmallCampaignList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationServiceDailyBudgetSmall {\n");
    sb.append("    dailyBudgetSmallCampaignList: ").append(toIndentedString(dailyBudgetSmallCampaignList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

