/*
 * Yahoo!広告 ディスプレイ広告 API リファレンス / Yahoo! JAPAN Ads Display Ads API Reference
 * <div lang=\"ja\">Yahoo!広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v6/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v6.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;PlacementUrlIdeaServiceAdFormatConditionsオブジェクトは、広告掲載フォーマットの情報を保持するオブジェクトです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;PlacementUrlIdeaServiceAdFormatConditions stores Ad Distribution format information.&lt;/div&gt; 
 */
@ApiModel(description = "<div lang=\"ja\">PlacementUrlIdeaServiceAdFormatConditionsオブジェクトは、広告掲載フォーマットの情報を保持するオブジェクトです。</div> <div lang=\"en\">PlacementUrlIdeaServiceAdFormatConditions stores Ad Distribution format information.</div> ")
@JsonPropertyOrder({
  PlacementUrlIdeaServiceAdFormatConditions.JSON_PROPERTY_AD_STYLE,
  PlacementUrlIdeaServiceAdFormatConditions.JSON_PROPERTY_MEDIA_AD_FORMAT
})
@JsonTypeName("PlacementUrlIdeaServiceAdFormatConditions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PlacementUrlIdeaServiceAdFormatConditions {
  public static final String JSON_PROPERTY_AD_STYLE = "adStyle";
  private String adStyle;

  public static final String JSON_PROPERTY_MEDIA_AD_FORMAT = "mediaAdFormat";
  private String mediaAdFormat;

  public PlacementUrlIdeaServiceAdFormatConditions() { 
  }

  public PlacementUrlIdeaServiceAdFormatConditions adStyle(String adStyle) {
    
    this.adStyle = adStyle;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;広告スタイルです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Ad style.&lt;/div&gt; 
   * @return adStyle
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">広告スタイルです。</div> <div lang=\"en\">Ad style.</div> ")
  @JsonProperty(JSON_PROPERTY_AD_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAdStyle() {
    return adStyle;
  }


  @JsonProperty(JSON_PROPERTY_AD_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdStyle(String adStyle) {
    this.adStyle = adStyle;
  }


  public PlacementUrlIdeaServiceAdFormatConditions mediaAdFormat(String mediaAdFormat) {
    
    this.mediaAdFormat = mediaAdFormat;
    return this;
  }

   /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;メディアフォーマットです。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Media format.&lt;/div&gt; 
   * @return mediaAdFormat
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<div lang=\"ja\">メディアフォーマットです。</div> <div lang=\"en\">Media format.</div> ")
  @JsonProperty(JSON_PROPERTY_MEDIA_AD_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMediaAdFormat() {
    return mediaAdFormat;
  }


  @JsonProperty(JSON_PROPERTY_MEDIA_AD_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMediaAdFormat(String mediaAdFormat) {
    this.mediaAdFormat = mediaAdFormat;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlacementUrlIdeaServiceAdFormatConditions placementUrlIdeaServiceAdFormatConditions = (PlacementUrlIdeaServiceAdFormatConditions) o;
    return Objects.equals(this.adStyle, placementUrlIdeaServiceAdFormatConditions.adStyle) &&
        Objects.equals(this.mediaAdFormat, placementUrlIdeaServiceAdFormatConditions.mediaAdFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adStyle, mediaAdFormat);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlacementUrlIdeaServiceAdFormatConditions {\n");
    sb.append("    adStyle: ").append(toIndentedString(adStyle)).append("\n");
    sb.append("    mediaAdFormat: ").append(toIndentedString(mediaAdFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

