/*
 * LINEヤフー広告 ディスプレイ広告 API リファレンス / LY Ads Display Ads API Reference
 * <div lang=\"ja\">LINEヤフー広告 ディスプレイ広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Display Ads API Web Services supported in LY Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/design/v19/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-display-api-documents/blob/master/bestpractice/en\">Best Practice</a></div> 
 *
 * The version of the OpenAPI document: v19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package jp.co.yahoo.adsdisplayapi.v19.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import jp.co.yahoo.adsdisplayapi.v19.model.Error;
import jp.co.yahoo.adsdisplayapi.v19.model.Recommendation;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;RecommendationServiceValueオブジェクトは、操作結果を含むRecommendationの情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;RecommendationServiceValue object describes recommendation information including its operation results.&lt;/div&gt; 
 */
@JsonPropertyOrder({
  RecommendationServiceValue.JSON_PROPERTY_ERRORS,
  RecommendationServiceValue.JSON_PROPERTY_RECOMMENDATION,
  RecommendationServiceValue.JSON_PROPERTY_OPERATION_SUCCEEDED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class RecommendationServiceValue {
  public static final String JSON_PROPERTY_ERRORS = "errors";
  @jakarta.annotation.Nullable
  private List<Error> errors;

  public static final String JSON_PROPERTY_RECOMMENDATION = "recommendation";
  @jakarta.annotation.Nullable
  private Recommendation recommendation;

  public static final String JSON_PROPERTY_OPERATION_SUCCEEDED = "operationSucceeded";
  @jakarta.annotation.Nullable
  private Boolean operationSucceeded;

  public RecommendationServiceValue() {
  }

  public RecommendationServiceValue errors(@jakarta.annotation.Nullable List<Error> errors) {
    
    this.errors = errors;
    return this;
  }

  public RecommendationServiceValue addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;エラー内容です。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Error content.&lt;/div&gt; 
   * @return errors
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Error> getErrors() {
    return errors;
  }


  @JsonProperty(value = JSON_PROPERTY_ERRORS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrors(@jakarta.annotation.Nullable List<Error> errors) {
    this.errors = errors;
  }

  public RecommendationServiceValue recommendation(@jakarta.annotation.Nullable Recommendation recommendation) {
    
    this.recommendation = recommendation;
    return this;
  }

  /**
   * Get recommendation
   * @return recommendation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECOMMENDATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Recommendation getRecommendation() {
    return recommendation;
  }


  @JsonProperty(value = JSON_PROPERTY_RECOMMENDATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecommendation(@jakarta.annotation.Nullable Recommendation recommendation) {
    this.recommendation = recommendation;
  }

  public RecommendationServiceValue operationSucceeded(@jakarta.annotation.Nullable Boolean operationSucceeded) {
    
    this.operationSucceeded = operationSucceeded;
    return this;
  }

  /**
   * &lt;div lang&#x3D;\&quot;ja\&quot;&gt;処理結果です。trueの場合は、処理は成功しました。falseの場合は処理が失敗しています。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;The process results. If true, the process succeeded. If false, the process failed.&lt;/div&gt; 
   * @return operationSucceeded
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_OPERATION_SUCCEEDED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getOperationSucceeded() {
    return operationSucceeded;
  }


  @JsonProperty(value = JSON_PROPERTY_OPERATION_SUCCEEDED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperationSucceeded(@jakarta.annotation.Nullable Boolean operationSucceeded) {
    this.operationSucceeded = operationSucceeded;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecommendationServiceValue recommendationServiceValue = (RecommendationServiceValue) o;
    return Objects.equals(this.errors, recommendationServiceValue.errors) &&
        Objects.equals(this.recommendation, recommendationServiceValue.recommendation) &&
        Objects.equals(this.operationSucceeded, recommendationServiceValue.operationSucceeded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errors, recommendation, operationSucceeded);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecommendationServiceValue {\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    recommendation: ").append(toIndentedString(recommendation)).append("\n");
    sb.append("    operationSucceeded: ").append(toIndentedString(operationSucceeded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

}

